name: Test PowerShell on Ubuntu
on: push

jobs:
  IPAddress-testing:
    name: unit tests validation
    runs-on: ubuntu-latest
    steps:
      - name: Perform a validation of class IPAddress file
        shell: pwsh
        run: |
          Invoke-Pester -PassThru -Path /home/runner/work/