name: Test PowerShell on Ubuntu
on: push

jobs:
  IPAddress-testing:
    name: IPAddress class testing
    runs-on: ubuntu-latest
    steps:
      - name: Perform a validation of class IPAddress file
        shell: pwsh
        run: *.tests.ps1 |
          Invoke-Pester -PassThru