name: Test PowerShell on Ubuntu
on: push

jobs:
  IPAddress-testing:
    name: IPAddress class testing
    runs-on: ubuntu-latest
    steps:
      - name: Loading powershell
        uses: charchess/SCCM-Library@master
      - name: Perform a validation of class IPAddress file
        shell: pwsh
        run: |
          Invoke-Pester -PassThru
