name: Test PowerShell on Ubuntu
on: push

jobs:
  test-pwsh:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Run Pester tests
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force
          $pester=Invoke-Pester -Path "tests" -Passthru
          if ($pester.Result -eq 'Failed') {exit 1}
        shell: pwsh
