name: Test PowerShell on Ubuntu
on: push

jobs:
  IPAddress-testing:
    name: unit tests validation
    runs-on: ubuntu-latest
    steps:
      - name: Perform a validation of class IPAddress file
        shell: pwsh
        run: |
          get-childitem -recurse -Path /home/runner/work/SCCM-Library/docker
        #  Invoke-Pester -PassThru -Path /home/runner/work/SCCM-Library/.github/workflows/IP.Tests.ps1