name: Test PowerShell on Ubuntu
on: push

jobs:
  test-pwsh:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Run Pester tests
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force
          Invoke-Pester -Path "tests" -Passthru -CodeCoverage
          if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
        shell: pwsh
